In [1]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5]])
b=np.array([[3,6,6,7],[2,5,6,7]])
print(np.multiply(a,b))

[[ 3 12 18 28]
 [ 4 15 24 35]]


In [2]:
#5*5
num=np.arange(25).reshape(-1,5)
print(num)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [3]:
n=num[:,::-1]

In [4]:
n

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20]])

In [5]:
k=num[::-1,::-1]

In [6]:
k

array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [7]:
import numpy as np
x=np.zeros_like(k)
print(x)
print(x.dtype)



[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
int32


In [8]:
num=np.array([[1,2,3,4],[5,3,3,8],[3,7,9,3]])
print(num)
n=3
r="manasa"
print(np.where(num==n,r,num))
print(np.where(num>n,r,num))
print(np.where(num<n,r,num))


[[1 2 3 4]
 [5 3 3 8]
 [3 7 9 3]]
[['1' '2' 'manasa' '4']
 ['5' 'manasa' 'manasa' '8']
 ['manasa' '7' '9' 'manasa']]
[['1' '2' '3' 'manasa']
 ['manasa' '3' '3' 'manasa']
 ['3' 'manasa' 'manasa' '3']]
[['manasa' 'manasa' '3' '4']
 ['5' '3' '3' '8']
 ['3' '7' '9' '3']]


In [9]:
print(num[num>n])

[4 5 8 7 9]


In [10]:
print(num)

[[1 2 3 4]
 [5 3 3 8]
 [3 7 9 3]]


In [11]:
#sort through rows
print(np.sort(num))

[[1 2 3 4]
 [3 3 5 8]
 [3 3 7 9]]


In [12]:
#sort through column
print(np.sort(num,axis=0))

[[1 2 3 3]
 [3 3 3 4]
 [5 7 9 8]]


In [13]:
print(np.zeros(shape=(5,6)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [14]:
#reversing an array
import numpy as np
a=np.arange(1,51)
a
print(a[::-1])

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1]


In [15]:
n=a.astype("float")

In [16]:
n

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [17]:
#adding border
x=np.ones((4,4))
print(x)
y=np.pad(x,pad_width=2,mode="constant",constant_values=2)
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 1. 1. 1. 1. 2. 2.]
 [2. 2. 1. 1. 1. 1. 2. 2.]
 [2. 2. 1. 1. 1. 1. 2. 2.]
 [2. 2. 1. 1. 1. 1. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]]


In [18]:
z=np.append(a,x)
print(z)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [19]:
x=np.empty((3,4))
y=np.full((3,4),7)

In [20]:
print(x)
print(y)

[[1.52791995e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [2.67017691e-306 6.82116729e-043 6.56447986e-091 9.41706232e-047]
 [1.29164936e+160 1.69340608e-052 3.99910963e+252 4.93432906e+257]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
