In [2]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
print(a)

[1 2 3 4]


In [5]:
type(a)


numpy.ndarray

In [4]:
b=np.array([[1,2,3],[8,9,0]])
b

array([[1, 2, 3],
       [8, 9, 0]])

In [6]:
c=np.array([[[1,2,3],[8,9,0]],[[3,4,5],[3,5,6]]])
c

array([[[1, 2, 3],
        [8, 9, 0]],

       [[3, 4, 5],
        [3, 5, 6]]])

In [7]:
a.ndim
b.ndim
c.ndim


3

In [8]:
b.ndim

2

In [9]:
a.ndim

1

In [10]:
x=np.array([1,2,3,4],ndmin=6)

In [11]:
x

array([[[[[[1, 2, 3, 4]]]]]])

In [12]:
b=np.array([[1,2,3],[8,9,0]])
b[0,1]

2

In [13]:
c=np.array([[[1,2,3],[8,9,0]],[[3,4,5],[3,5,6]]])
c[0,1]

array([8, 9, 0])

In [14]:
c[0,1,1]

9

In [15]:
c[0,1,-1]

0

In [17]:
y=np.arange(1,50,5)

In [18]:
y

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [20]:
n=np.zeros(10)

In [21]:
n

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
m=np.ones(10)

In [23]:
m

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
g=np.empty(5)
g


array([2.12199579e-314, 8.80628253e-312, 4.24896455e-321, 8.80628254e-312,
       0.00000000e+000])

In [27]:
g=np.empty(5)
g


























array([2.12199579e-314, 8.80628253e-312, 4.24896455e-321, 8.80628254e-312,
       0.00000000e+000])

In [28]:
g=np.empty(5)
g


array([2.12199579e-314, 8.80628253e-312, 4.24896455e-321, 8.80628254e-312,
       0.00000000e+000])

In [29]:
print(a.dtype)

int32


In [30]:
b.dtype

dtype('int32')

In [4]:
import numpy as np
a=np.ones(2)
a

array([1., 1.])

In [5]:
b=np.array([1,2,3,4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [6]:
b.max()

6

In [7]:
b.min()

1

In [8]:
b.sum()

21

In [13]:
c=np.array([1,2,3,4,5,6])
c

array([1, 2, 3, 4, 5, 6])

In [14]:
c.sum()

21

In [22]:
c.dtype.name

'int32'

In [17]:
b=np.array([1,2,3,4,5,6,"manasa"])
b

array(['1', '2', '3', '4', '5', '6', 'manasa'], dtype='<U11')

In [19]:
b.dtype.name

'str352'

In [31]:
#shape 
a=np.array([[1,2,3,4],[8,6,7],9])
a.shape

C:\Users\MANASA BOJJA\AppData\Local\Temp\ipykernel_10344\1062226222.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[1,2,3,4],[8,6,7],9])


(3,)

In [36]:
b=np.array([1,2,4,5,7],ndmin=6)
print(b)
b.shape

[[[[[[1 2 4 5 7]]]]]]


(1, 1, 1, 1, 1, 5)

In [41]:
a=np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [42]:
#reshape 1d to 3d
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [44]:
a=np.arange(15).reshape(5,3)
a
print(a.reshape(5,3).base)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [46]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
n=a.reshape(2,2,-1)
print(n)
print(n.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)


In [52]:
#multidimension to 1D
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
n=a.reshape(-1)
print(n)


(2, 3)
[1 2 3 4 5 6]


In [55]:
#slicing
a=np.array([1,2,3,4,5,6,7,8])
print(a[1:5])
print(a[4: ])
print(a[:5])
print(a[-3:-1])
print(a[1:5:2])
print(a[::3])

[2 3 4 5]
[5 6 7 8]
[1 2 3 4 5]
[6 7]
[2 4]
[1 4 7]


In [57]:
#2d slicing
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a[0,1:3])

[2 3]


In [27]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a[0:2,3])

[4 8]


In [61]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a[0:2,0:3])

[[1 2 3]
 [5 6 7]]


In [4]:
#datatypes
import numpy as np
a=np.array(["manasa","swaroop","hello"])
print(a.dtype.name)

str224


In [5]:
b=np.array([1,2,3,4],dtype="S")
print(b)
print(b.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [6]:
b=np.array([1,2,3,4],dtype="i")
print(b)
print(b.dtype)

[1 2 3 4]
int32


In [7]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [11]:
import numpy as np

arr = np.array([1.1, 2.1, 0])

newarr = arr.astype('bool')

print(newarr)
print(newarr.dtype)

[ True  True False]
bool


In [12]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [13]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8


In [14]:
import numpy as np

arr = np.array([1, 2, 3])
for i in np.nditer(arr,flags=["buffered"],op_dtypes=['S']):
    print(i)


b'1'
b'2'
b'3'


In [17]:
for i, x in np.ndenumerate(arr):
    print(i,x)

(0,) 1
(1,) 2
(2,) 3


In [18]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for i, x in np.ndenumerate(arr):
    print(i,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [19]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [20]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [22]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
arr=np.stack((arr1,arr2))
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [25]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [1]:
import numpy as np

arr1 = np.array([1, 2, 3,4])

arr2 = np.array([4, 5, 6,5])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]
  [4 5]]]


In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
n=np.array_split(arr,5)
n

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]

In [33]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [34]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [35]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [37]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6], dtype=int64),)


In [38]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [39]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [40]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [3]:
import numpy as np
a=np.array([[1,2,3,4],[3,5,6,8]])
b=np.array([[5,6,7,8],[3,4,5,6]])
print(np.multiply(a,b))

[[ 5 12 21 32]
 [ 9 20 30 48]]


In [5]:
import numpy as np
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])
print(nums)
n=print(nums(::-1,::-1))
print(n)

SyntaxError: invalid syntax (4077831208.py, line 7)