In [1]:
#series
import pandas as pd
a=[1,2,3,4]
b=[3,4,5,6]
print(pd.Series([a,b]))

0    [1, 2, 3, 4]
1    [3, 4, 5, 6]
dtype: object


In [2]:
m=pd.Series(a,index=["m1","m2","m3","m4"])
print(m)

m1    1
m2    2
m3    3
m4    4
dtype: int64


In [3]:
print(m["m2"])

2


In [47]:
import pandas as pd
s={"manasa":100,"swaroop":100,"praveen":90,"lavs":90}
print(pd.Series(s))

manasa     100
swaroop    100
praveen     90
lavs        90
dtype: int64


In [5]:
print(s["swaroop"])

100


In [6]:
print(pd.Series(s,index=["swaroop","manasa"]))

swaroop    100
manasa     100
dtype: int64


In [54]:
#datframe
student={
    "Name":["manasa","raji","swaroop","praveen"],
    "marks":[100,90,80,70],
    "age":[19,18,18,19]
}
a=pd.DataFrame(student,index=["a","b","c","d"])
print(a)

      Name  marks  age
a   manasa    100   19
b     raji     90   18
c  swaroop     80   18
d  praveen     70   19


In [57]:
print(a.loc[b:c])

InvalidIndexError: [-10   9   8   7   6]

In [9]:
a=pd.DataFrame(student,index=[1,2,3,4])

In [10]:
print(a)

      Name  marks  age
1   manasa    100   19
2     raji     90   18
3  swaroop     80   18
4  praveen     70   19


In [11]:
#indexing using series
s=pd.Series(["india","pakistan","iran","iraq"],index=["one","two","three","four"])
print(s)
#positional indexing
print(s[1])
print(s[[1,3]])
print(111111111)
#label indexing
print(s["four"])
print(s[["one","three"]])

one         india
two      pakistan
three        iran
four         iraq
dtype: object
pakistan
two     pakistan
four        iraq
dtype: object
111111111
iraq
one      india
three     iran
dtype: object


In [12]:
#changing index
s.index=[1,2,3,4]
s

1       india
2    pakistan
3        iran
4        iraq
dtype: object

In [13]:
import pandas as pd
s=pd.Series(["india","pakistan","iran","iraq"],index=["one","two","three","four"])
#slicing
#slice through index
print(s[1:3])
#slice through label
print(s["one":"four"])

two      pakistan
three        iran
dtype: object
one         india
two      pakistan
three        iran
four         iraq
dtype: object


In [14]:
#reverse
print(s[: : -1])

four         iraq
three        iran
two      pakistan
one         india
dtype: object


In [15]:
#modification using slicing
s[1:3]="india"
print(s)

one      india
two      india
three    india
four      iraq
dtype: object


In [16]:
s["one":"three"]="russia"
print(s)

one      russia
two      russia
three    russia
four       iraq
dtype: object


In [17]:
#attributes
s.name="capital"
s

one      russia
two      russia
three    russia
four       iraq
Name: capital, dtype: object

In [18]:
s.index.name="Number"
s

Number
one      russia
two      russia
three    russia
four       iraq
Name: capital, dtype: object

In [19]:
print(s.values)

['russia' 'russia' 'russia' 'iraq']


In [20]:
print(s.size)

4


In [21]:
print(s.empty)

False


In [22]:
k=pd.Series()
print(k.empty)

True


C:\Users\MANASA BOJJA\AppData\Local\Temp\ipykernel_2424\2485116252.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  k=pd.Series()


In [23]:
#mathematical operations
import pandas as pd
a=pd.Series([10,5,7,8,9])
b=pd.Series([4,5,6,7])
print(a)
print(b)
print(a+b)

0    10
1     5
2     7
3     8
4     9
dtype: int64
0    4
1    5
2    6
3    7
dtype: int64
0    14.0
1    10.0
2    13.0
3    15.0
4     NaN
dtype: float64


In [24]:
print(a.add(b,fill_value=5))

0    14.0
1    10.0
2    13.0
3    15.0
4    14.0
dtype: float64


In [25]:
print(a-b)

0    6.0
1    0.0
2    1.0
3    1.0
4    NaN
dtype: float64


In [26]:
print(a.sub(b,fill_value=5))

0    6.0
1    0.0
2    1.0
3    1.0
4    4.0
dtype: float64


In [27]:
print(a*b)

0    40.0
1    25.0
2    42.0
3    56.0
4     NaN
dtype: float64


In [28]:
print(a.mul(b,fill_value=5))

0    40.0
1    25.0
2    42.0
3    56.0
4    45.0
dtype: float64


In [29]:
print(a/b)

0    2.500000
1    1.000000
2    1.166667
3    1.142857
4         NaN
dtype: float64


In [30]:
import numpy as np
print(a.count())
x=pd.Series(np.arange(1,11,1))
x

5


0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int32

In [31]:
#empty dataframe
import pandas as pd
d=pd.DataFrame()
print(d)

Empty DataFrame
Columns: []
Index: []


In [32]:
#using numpy arrays
import numpy as np
import pandas as pd
a=np.array([1,2,3,4,5])
b=np.array([-10,9,8,7,6])
c=np.array(["manasa","neeraja","hello"])
x=pd.DataFrame([a,b,c],columns=["A","B","C","D","E"])
print(x)


        A        B      C    D    E
0       1        2      3  4.0  5.0
1     -10        9      8  7.0  6.0
2  manasa  neeraja  hello  NaN  NaN


In [33]:
#list of dictionary
l=[{"a":10,"b":100,"c":34},{"a":13,"b":19,"c":90}]
d=pd.DataFrame(l)
d

a    b   c
0  10  100  34
1  13   19  90

In [34]:
l=[{"a":10,"b":100,"c":34},{"x":13,"b":19,"c":90}]
d=pd.DataFrame(l)
d

a    b   c     x
0  10.0  100  34   NaN
1   NaN   19  90  13.0

In [35]:
#dictionary of lists
y={
    "state":["AP","UP","TELENGANA"],
    "Capital":["amaravathi","simla","hyderabad"],
    "salary":[100,600,900]
}
x=pd.DataFrame(y)
x

state     Capital  salary
0         AP  amaravathi     100
1         UP       simla     600
2  TELENGANA   hyderabad     900

In [36]:
#changing columns
y={
    "state":["AP","UP","TELENGANA"],
    "Capital":["amaravathi","simla","hyderabad"],
    "salary":[100,600,900]
}
x=pd.DataFrame(y,columns=["state","salary","Capital"])
x


state  salary     Capital
0         AP     100  amaravathi
1         UP     600       simla
2  TELENGANA     900   hyderabad

In [37]:
#dataframe from series
seriesA = pd.Series([1,2,3,4,5],
 index = ['a', 'b', 'c', 'd', 'e'])
seriesB = pd.Series ([1000,2000,-1000,-5000,1000],
 index = ['a', 'b', 'c', 'd', 'e'])
seriesC = pd.Series([10,20,-10,-50,100],
 index = ['z', 'y', 'a', 'c', 'e'])
d1=pd.DataFrame(seriesA)
d1



0
a  1
b  2
c  3
d  4
e  5

In [38]:
d2=pd.DataFrame([seriesA,seriesB,seriesC])
d2

a       b       c       d       e     z     y
0     1.0     2.0     3.0     4.0     5.0   NaN   NaN
1  1000.0  2000.0 -1000.0 -5000.0  1000.0   NaN   NaN
2   -10.0     NaN   -50.0     NaN   100.0  10.0  20.0

In [39]:
#creation from dictionary of series
RS={
    "manasa":pd.Series([100,90,80],index=["CD","COA","DSP"]),
    "praveen":pd.Series([40,90,80],index=["CD","COA","DSP"]),
    "ruchi":pd.Series([90,80,70],index=["CD","COA","DSP"])
}
d3=pd.DataFrame(RS)
d3

manasa  praveen  ruchi
CD      100       40     90
COA      90       90     80
DSP      80       80     70

In [40]:
type(d3.manasa)

pandas.core.series.Series

In [41]:
RS={
    "manasa":pd.Series([100,90,80],index=["CD","COA","DSP"]),
    "praveen":pd.Series([40,90,80],index=["CD","COA","DSP"]),
    "ruchi":pd.Series([90,80,70,40],index=["CD","COA","DSP","WT"])
}
d4=pd.DataFrame(RS)
d4

manasa  praveen  ruchi
CD    100.0     40.0     90
COA    90.0     90.0     80
DSP    80.0     80.0     70
WT      NaN      NaN     40

In [42]:
#adding coulmn
d4["swaroop"]=[20,90,50,90]
d4

manasa  praveen  ruchi  swaroop
CD    100.0     40.0     90       20
COA    90.0     90.0     80       90
DSP    80.0     80.0     70       50
WT      NaN      NaN     40       90

In [43]:
#updating column
d4["praveen"]=[20,40,90,80]
d4

manasa  praveen  ruchi  swaroop
CD    100.0       20     90       20
COA    90.0       40     80       90
DSP    80.0       90     70       50
WT      NaN       80     40       90

In [44]:
d4["ruchi"]=90
d4

manasa  praveen  ruchi  swaroop
CD    100.0       20     90       20
COA    90.0       40     90       90
DSP    80.0       90     90       50
WT      NaN       80     90       90

In [45]:
#adding row
d4.loc["OR"]=[40,90,70,90,60]
d4

ValueError: cannot set a row with mismatched columns

In [ ]:
d4[: ]=0
d4

In [ ]:
d4

In [61]:
RS={
    "manasa":pd.Series([100,90,80],index=["CD","COA","DSP"]),
    "praveen":pd.Series([40,90,80],index=["CD","COA","DSP"]),
    "ruchi":pd.Series([90,80,70,40],index=["CD","COA","DSP","WT"])
}
d4=pd.DataFrame(RS)
d4


manasa  praveen  ruchi
CD    100.0     40.0     90
COA    90.0     90.0     80
DSP    80.0     80.0     70
WT      NaN      NaN     40

In [62]:
#deleting row
print(d4)
d4=d4.drop("WT",axis=0)
d4


     manasa  praveen  ruchi
CD    100.0     40.0     90
COA    90.0     90.0     80
DSP    80.0     80.0     70
WT      NaN      NaN     40


manasa  praveen  ruchi
CD    100.0     40.0     90
COA    90.0     90.0     80
DSP    80.0     80.0     70

In [63]:
d4["hello"]=[20,90,40]
d4

manasa  praveen  ruchi  hello
CD    100.0     40.0     90     20
COA    90.0     90.0     80     90
DSP    80.0     80.0     70     40

In [64]:
print(d4)
d4=d4.drop(["ruchi","hello"],axis=1)
d4

     manasa  praveen  ruchi  hello
CD    100.0     40.0     90     20
COA    90.0     90.0     80     90
DSP    80.0     80.0     70     40


manasa  praveen
CD    100.0     40.0
COA    90.0     90.0
DSP    80.0     80.0

In [65]:
import pandas as pd
RS={
    "manasa":pd.Series([100,90,80],index=["CD","COA","DSP"]),
    "praveen":pd.Series([40,90,80],index=["CD","COA","DSP"]),
    "ruchi":pd.Series([90,80,70,40,80],index=["CD","COA","DSP","WT","OR"])
}
d4=pd.DataFrame(RS)
d4


manasa  praveen  ruchi
CD    100.0     40.0     90
COA    90.0     90.0     80
DSP    80.0     80.0     70
OR      NaN      NaN     80
WT      NaN      NaN     40

In [ ]:
d4

In [66]:
#renaming row labels
d4=d4.rename({"CD":"S1","COA":"S2","DSP":"S3","OR":"S4","WT":"S5"},axis="index")
print(d4)

    manasa  praveen  ruchi
S1   100.0     40.0     90
S2    90.0     90.0     80
S3    80.0     80.0     70
S4     NaN      NaN     80
S5     NaN      NaN     40


In [67]:
d4=d4.rename({"S1":"CD","S2":"COA"},axis="index")
print(d4)

     manasa  praveen  ruchi
CD    100.0     40.0     90
COA    90.0     90.0     80
S3     80.0     80.0     70
S4      NaN      NaN     80
S5      NaN      NaN     40


In [68]:
#renaming coulmns
d4=d4.rename({"manasa":"swaroop","praveen":"haseena","ruchi":"sai"},axis="columns")
d4

swaroop  haseena  sai
CD     100.0     40.0   90
COA     90.0     90.0   80
S3      80.0     80.0   70
S4       NaN      NaN   80
S5       NaN      NaN   40

In [69]:
#label based indexing

print(d4.loc["COA"])
print(d4.loc[["CD","COA"]])


swaroop    90.0
haseena    90.0
sai        80.0
Name: COA, dtype: float64
     swaroop  haseena  sai
CD     100.0     40.0   90
COA     90.0     90.0   80


In [ ]:
#coulmn
print(d4["swaroop"])
print(d4.loc[:,"swaroop"])

In [70]:
#boolean indexing
print(d4.loc["CD"]>90)

swaroop     True
haseena    False
sai        False
Name: CD, dtype: bool


In [ ]:
print(d4["swaroop"]>90)
print(d4.loc[:,"swaroop"]>90)


In [71]:
#slicing
print(d4)
print(d4.loc["CD":"S4"])#row slicing
print(d4.loc["CD":"S4","swaroop"])#accesing particualr coulmn
print("!!!!!!!!!")
print(d4.loc["CD":"S4","swaroop"])
print("!!!!!!!")
print(d4.loc["CD":"S4","swaroop":"sai"])#multiple coulmns
print(d4.loc["CD":"S4",["swaroop","sai"]])





     swaroop  haseena  sai
CD     100.0     40.0   90
COA     90.0     90.0   80
S3      80.0     80.0   70
S4       NaN      NaN   80
S5       NaN      NaN   40
     swaroop  haseena  sai
CD     100.0     40.0   90
COA     90.0     90.0   80
S3      80.0     80.0   70
S4       NaN      NaN   80
CD     100.0
COA     90.0
S3      80.0
S4       NaN
Name: swaroop, dtype: float64
!!!!!!!!!
CD     100.0
COA     90.0
S3      80.0
S4       NaN
Name: swaroop, dtype: float64
!!!!!!!
     swaroop  haseena  sai
CD     100.0     40.0   90
COA     90.0     90.0   80
S3      80.0     80.0   70
S4       NaN      NaN   80
     swaroop  sai
CD     100.0   90
COA     90.0   80
S3      80.0   70
S4       NaN   80


In [72]:
#joining
d1=pd.DataFrame([[1, 2, 3], [4, 5], 
[6]], columns=['C1', 'C2', 'C3'], index=['R1', 
'R2', 'R3'])
d1


C1   C2   C3
R1   1  2.0  3.0
R2   4  5.0  NaN
R3   6  NaN  NaN

In [73]:
 d2=pd.DataFrame([[10, 20], [30], [40, 
50]], columns=['C2', 'C5'], index=['R4', 'R2', 
'R5'])
d2
    

C2    C5
R4  10  20.0
R2  30   NaN
R5  40  50.0

In [74]:
print(d1.append(d2))

     C1    C2   C3    C5
R1  1.0   2.0  3.0   NaN
R2  4.0   5.0  NaN   NaN
R3  6.0   NaN  NaN   NaN
R4  NaN  10.0  NaN  20.0
R2  NaN  30.0  NaN   NaN
R5  NaN  40.0  NaN  50.0


C:\Users\MANASA BOJJA\AppData\Local\Temp\ipykernel_2424\1361826665.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(d1.append(d2))


In [75]:
print(d2.append(d1))

      C2    C5   C1   C3
R4  10.0  20.0  NaN  NaN
R2  30.0   NaN  NaN  NaN
R5  40.0  50.0  NaN  NaN
R1   2.0   NaN  1.0  3.0
R2   5.0   NaN  4.0  NaN
R3   NaN   NaN  6.0  NaN


C:\Users\MANASA BOJJA\AppData\Local\Temp\ipykernel_2424\3867743262.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(d2.append(d1))


In [76]:
x=d2.append(d1,sort=True)
y=d2.append(d1,sort=False)


C:\Users\MANASA BOJJA\AppData\Local\Temp\ipykernel_2424\3636398444.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  x=d2.append(d1,sort=True)
C:\Users\MANASA BOJJA\AppData\Local\Temp\ipykernel_2424\3636398444.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y=d2.append(d1,sort=False)


In [77]:
print(d1.append(d2,ignore_index=True))

    C1    C2   C3    C5
0  1.0   2.0  3.0   NaN
1  4.0   5.0  NaN   NaN
2  6.0   NaN  NaN   NaN
3  NaN  10.0  NaN  20.0
4  NaN  30.0  NaN   NaN
5  NaN  40.0  NaN  50.0


C:\Users\MANASA BOJJA\AppData\Local\Temp\ipykernel_2424\1071641200.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(d1.append(d2,ignore_index=True))


In [78]:
FA = {
 'Assam' :pd.Series([78438, 2797, 
10192, 15116], index = ['GeoArea', 'VeryDense', 
'ModeratelyDense', 'OpenForest']),
 'Kerala' :pd.Series([ 38852, 1663, 
9407, 9251], index = ['GeoArea' ,'VeryDense', 
'ModeratelyDense', 'OpenForest']),
 'Delhi' :pd.Series([1483, 6.72, 56.24, 
129.45], index = ['GeoArea', 'VeryDense', 
'ModeratelyDense', 'OpenForest'])}
FAD = pd.DataFrame(FA)
FAD




Assam  Kerala    Delhi
GeoArea          78438   38852  1483.00
VeryDense         2797    1663     6.72
ModeratelyDense  10192    9407    56.24
OpenForest       15116    9251   129.45

In [79]:
print(FAD.index)

Index(['GeoArea', 'VeryDense', 'ModeratelyDense', 'OpenForest'], dtype='object')


In [80]:
print(FAD.columns)

Index(['Assam', 'Kerala', 'Delhi'], dtype='object')


In [81]:
print(FAD.dtypes)

Assam       int64
Kerala      int64
Delhi     float64
dtype: object


In [82]:
print(FAD.values)

[[7.8438e+04 3.8852e+04 1.4830e+03]
 [2.7970e+03 1.6630e+03 6.7200e+00]
 [1.0192e+04 9.4070e+03 5.6240e+01]
 [1.5116e+04 9.2510e+03 1.2945e+02]]


In [83]:
print(FAD.shape)

(4, 3)


In [84]:
print(FAD.size)

12


In [85]:
print(FAD.T)

        GeoArea  VeryDense  ModeratelyDense  OpenForest
Assam   78438.0    2797.00         10192.00    15116.00
Kerala  38852.0    1663.00          9407.00     9251.00
Delhi    1483.0       6.72            56.24      129.45


In [86]:
print(FAD.head())


                 Assam  Kerala    Delhi
GeoArea          78438   38852  1483.00
VeryDense         2797    1663     6.72
ModeratelyDense  10192    9407    56.24
OpenForest       15116    9251   129.45


In [87]:
print(FAD.tail())

                 Assam  Kerala    Delhi
GeoArea          78438   38852  1483.00
VeryDense         2797    1663     6.72
ModeratelyDense  10192    9407    56.24
OpenForest       15116    9251   129.45


In [88]:
print(FAD.head(2))

           Assam  Kerala    Delhi
GeoArea    78438   38852  1483.00
VeryDense   2797    1663     6.72


In [ ]:
FAD

In [ ]:
FAD.to_csv(path_or_buf='c:/desktop/rt.csv',sep=",")

In [89]:
import pandas as pd
import numpy as np
p1=pd.Series([2,1,3,3,4,5])
p2=pd.Series([2,1,2,4,5])
p3=pd.Series([1,1,2,3,4,5])
p4=pd.Series([9,8,7,6,5])
p5=pd.Series([3,4,5,8,6,7])
print(p1.mean())
print(p1.median())
print(p1.mode())

3.0
3.0
0    3
dtype: int64
