In [27]:
from numpy import random
x=random.randint(10000000)#int
print(x)
y=random.rand()#float
z=random.rand(6)#list of float
print(y)
print(z)
a=random.randint(100,size=(10))#array
print(a)
b=random.randint(1000,size=(3,5))#2d array
print(b)


6485162
0.03634737918420694
[0.42808847 0.83446216 0.1231097  0.86071442 0.3996358  0.57024204]
[96 40 63 67  9 35 71 74 46 94]
[[854 863 678 457 565]
 [346 933 640 662 793]
 [280  16 625 401   8]]


In [28]:
import numpy as np
x=np.random.randint(100)
print(x)

74


In [25]:
x=random.choice([90,80,70,6,50])
print(x)
y=random.choice([90,80,70,6,50],size=(3,4,5))
print(y)

50
[[[ 6 80 80 90 90]
  [90  6 90 90 70]
  [70  6 50 50 50]
  [50 70 50  6 50]]

 [[90 50 90 70  6]
  [ 6 80 50 90 50]
  [90 50 80 50  6]
  [70 50  6 50 70]]

 [[80 80 50 80 80]
  [90  6 50 70 70]
  [ 6  6 90 90 70]
  [ 6 90  6 80 70]]]


In [30]:
from numpy import random#basedon the probability
x=random.choice([2,3,4,5],p=[0.1,0.5,0.0,0.4],size=50)
print(x)

[3 5 5 5 2 3 5 3 3 3 5 2 5 5 3 2 2 2 5 5 3 5 3 3 3 5 5 5 2 5 5 2 3 5 5 3 5
 2 3 3 5 5 3 5 5 5 3 3 3 3]


In [32]:
x=random.choice([2,3,4,5],p=[0.1,0.5,0.0,0.4],size=(3,5))
print(x)

[[5 5 3 3 5]
 [5 3 3 3 3]
 [2 3 5 3 3]]


In [39]:
import numpy as np
a=np.array([1,2,3,4])
random.shuffle(a)
print(a)

[3 1 2 4]


In [40]:
random.permutation(a)
print(a)

[3 1 2 4]
